// Adamson University Directory Data
const directoryData = [
    // SECURITY OFFICE
    { officeName: "BED GATE GUARD", localNumber: "127", phoneNumber: "", building: "SECURITY OFFICE", category: "Security", keywords: "bed gate guard security" },
    { officeName: "CS GATE GUARD", localNumber: "128", phoneNumber: "", building: "SECURITY OFFICE", category: "Security", keywords: "cs gate guard security" },
    { officeName: "MARIAN GUARD", localNumber: "142", phoneNumber: "", building: "SECURITY OFFICE", category: "Security", keywords: "marian guard security" },
    { officeName: "MERALCO GATE GUARD", localNumber: "147", phoneNumber: "", building: "SECURITY OFFICE", category: "Security", keywords: "meralco gate guard security" },
    { officeName: "OZ GATE GUARD", localNumber: "404", phoneNumber: "", building: "SECURITY OFFICE", category: "Security", keywords: "oz gate guard security" },
    { officeName: "SECURITY MAIN OFFICE", localNumber: "215", phoneNumber: "", building: "SECURITY OFFICE", category: "Security", keywords: "security main office" },
    { officeName: "ST GATE GUARD", localNumber: "252", phoneNumber: "", building: "SECURITY OFFICE", category: "Security", keywords: "st gate guard security" },
    { officeName: "SV GATE GUARD", localNumber: "913", phoneNumber: "", building: "SECURITY OFFICE", category: "Security", keywords: "sv gate guard security" },
    
    // HEALTH SERVICES (CLINIC)
    { officeName: "MAIN CLINIC @ ST Building", localNumber: "200", phoneNumber: "", building: "HEALTH SERVICES (CLINIC)", category: "Health", keywords: "main clinic st building health services" },
    { officeName: "CS BUILDING CLINIC", localNumber: "104", phoneNumber: "", building: "HEALTH SERVICES (CLINIC)", category: "Health", keywords: "cs building clinic health services" },
    { officeName: "SV BUILDING CLINIC", localNumber: "300", phoneNumber: "", building: "HEALTH SERVICES (CLINIC)", category: "Health", keywords: "sv building clinic health services" },
    
    // GUIDANCE OFFICE
    { officeName: "ARCHITECTURE/SHS-11 @ CS Building", localNumber: "157", phoneNumber: "", building: "GUIDANCE OFFICE", category: "Guidance", keywords: "architecture shs-11 cs building guidance" },
    { officeName: "BED/SHS-12 @ FRC Building", localNumber: "136", phoneNumber: "", building: "GUIDANCE OFFICE", category: "Guidance", keywords: "bed shs-12 frc building guidance" },
    { officeName: "BUSINESS ADMINISTRATION", localNumber: "247", phoneNumber: "", building: "GUIDANCE OFFICE", category: "Guidance", keywords: "business administration guidance" },
    { officeName: "ENGINEERING @ ST Building", localNumber: "229/445", phoneNumber: "", building: "GUIDANCE OFFICE", category: "Guidance", keywords: "engineering st building guidance" },
    { officeName: "MAIN OFFICE @ ST Building", localNumber: "207", phoneNumber: "", building: "GUIDANCE OFFICE", category: "Guidance", keywords: "main office st building guidance" },
    { officeName: "PLACEMENT @ ST Building", localNumber: "232", phoneNumber: "", building: "GUIDANCE OFFICE", category: "Guidance", keywords: "placement st building guidance" },
    { officeName: "SCIENCE/CELA/PHARMACY/NURSING", localNumber: "212", phoneNumber: "", building: "GUIDANCE OFFICE", category: "Guidance", keywords: "science cela pharmacy nursing guidance" },
    { officeName: "TESTING @ ST Building", localNumber: "241", phoneNumber: "", building: "GUIDANCE OFFICE", category: "Guidance", keywords: "testing st building guidance" },
    
    // MAINTENANCE
    { officeName: "AIRCON TECHNICIAN", localNumber: "120", phoneNumber: "", building: "MAINTENANCE", category: "Maintenance", keywords: "aircon technician maintenance" },
    { officeName: "CCTV TECHNICIAN", localNumber: "151", phoneNumber: "", building: "MAINTENANCE", category: "Maintenance", keywords: "cctv technician maintenance" },
    { officeName: "ELECTRICAL TECHNICIAN", localNumber: "777", phoneNumber: "", building: "MAINTENANCE", category: "Maintenance", keywords: "electrical technician maintenance" },
    { officeName: "HOUSEKEEPING", localNumber: "158", phoneNumber: "", building: "MAINTENANCE", category: "Maintenance", keywords: "housekeeping maintenance" },
    { officeName: "MOTOR POOL", localNumber: "144", phoneNumber: "", building: "MAINTENANCE", category: "Maintenance", keywords: "motor pool maintenance" },
    { officeName: "PLUMBER", localNumber: "424", phoneNumber: "", building: "MAINTENANCE", category: "Maintenance", keywords: "plumber maintenance" },
    { officeName: "TELEPHONE TECHNICIAN", localNumber: "555", phoneNumber: "", building: "MAINTENANCE", category: "Maintenance", keywords: "telephone technician maintenance" },
    { officeName: "PABX ROOM", localNumber: "306", phoneNumber: "", building: "MAINTENANCE", category: "Maintenance", keywords: "pabx room maintenance" },
    { officeName: "PABX ROOM 2", localNumber: "307", phoneNumber: "", building: "MAINTENANCE", category: "Maintenance", keywords: "pabx room 2 maintenance" },
    
    // CS BUILDING
    { officeName: "AAU TELEPHONE OPERATOR", localNumber: "0", phoneNumber: "", building: "CS BUILDING", category: "Administration", keywords: "aau telephone operator" },
    { officeName: "ACCOUNTING /STUDENTS ACCOUNTS", localNumber: "106", phoneNumber: "", building: "CS BUILDING", category: "Accounting", keywords: "accounting students accounts" },
    { officeName: "ACCOUNTING DIRECTOR", localNumber: "125", phoneNumber: "", building: "CS BUILDING", category: "Accounting", keywords: "accounting director" },
    { officeName: "ACCOUNTING OFFICE", localNumber: "135", phoneNumber: "", building: "CS BUILDING", category: "Accounting", keywords: "accounting office" },
    { officeName: "ARCHITECTURE FACULTY ROOM", localNumber: "146", phoneNumber: "", building: "CS BUILDING", category: "Faculty", keywords: "architecture faculty room" },
    { officeName: "ADMISSIONS OFFICE / A.S.R.O.", localNumber: "102", phoneNumber: "", building: "CS BUILDING", category: "Admissions", keywords: "admissions office asro" },
    { officeName: "A.S.R.O. DIRECTOR", localNumber: "342", phoneNumber: "", building: "CS BUILDING", category: "Administration", keywords: "asro director" },
    { officeName: "ARCHITECTURE DEAN'S OFFICE", localNumber: "132", phoneNumber: "", building: "CS BUILDING", category: "Academic", keywords: "architecture dean office" },
    { officeName: "BUDGET OFFICE", localNumber: "116", phoneNumber: "", building: "CS BUILDING", category: "Finance", keywords: "budget office" },
    { officeName: "CENTER FOR INNOVATIVE LEARNING", localNumber: "330", phoneNumber: "", building: "CS BUILDING", category: "Academic", keywords: "center innovative learning" },
    { officeName: "CASHIER'S OFFICE", localNumber: "145", phoneNumber: "", building: "CS BUILDING", category: "Finance", keywords: "cashier office" },
    { officeName: "CONTROLLER", localNumber: "112", phoneNumber: "", building: "CS BUILDING", category: "Finance", keywords: "controller" },
    { officeName: "GENERAL ACCOUNTING OFC.", localNumber: "140", phoneNumber: "", building: "CS BUILDING", category: "Accounting", keywords: "general accounting office" },
    { officeName: "H.R.M.D.O. DIRECTOR", localNumber: "239", phoneNumber: "", building: "CS BUILDING", category: "HR", keywords: "hrmdo director" },
    { officeName: "H.R.M.D.O. PAYROLL", localNumber: "251", phoneNumber: "", building: "CS BUILDING", category: "HR", keywords: "hrmdo payroll" },
    { officeName: "H.R.M.D.O. RECORDS", localNumber: "211", phoneNumber: "", building: "CS BUILDING", category: "HR", keywords: "hrmdo records" },
    { officeName: "H.R.M.D.O. RECRUITMENT", localNumber: "233", phoneNumber: "", building: "CS BUILDING", category: "HR", keywords: "hrmdo recruitment" },
    { officeName: "I.D.E.A. DIRECTOR", localNumber: "150", phoneNumber: "", building: "CS BUILDING", category: "Administration", keywords: "idea director" },
    { officeName: "I.D.E.A. PUBLICATION OFFICE", localNumber: "122", phoneNumber: "", building: "CS BUILDING", category: "Publications", keywords: "idea publication office" },
    { officeName: "I.D.E.A. PHOTOGRAPHY STUDIO", localNumber: "148", phoneNumber: "", building: "CS BUILDING", category: "Media", keywords: "idea photography studio" },
    { officeName: "INTERNAL AUDIT", localNumber: "126", phoneNumber: "", building: "CS BUILDING", category: "Finance", keywords: "internal audit" },
    { officeName: "LEGAL COUNSEL", localNumber: "141", phoneNumber: "", building: "CS BUILDING", category: "Legal", keywords: "legal counsel" },
    { officeName: "PRESIDENT'S OFFICE", localNumber: "114", phoneNumber: "", building: "CS BUILDING", category: "Administration", keywords: "president office" },
    { officeName: "PRESIDENT'S OFFICE - I.P.P.D.O.", localNumber: "118", phoneNumber: "", building: "CS BUILDING", category: "Administration", keywords: "president office ippdo" },
    { officeName: "PRESIDENTS OFFICE SECRETARY", localNumber: "115", phoneNumber: "", building: "CS BUILDING", category: "Administration", keywords: "presidents office secretary" },
    { officeName: "REGISTRAR DIRECTOR", localNumber: "154", phoneNumber: "", building: "CS BUILDING", category: "Registrar", keywords: "registrar director" },
    { officeName: "REGISTRAR INFORMATION", localNumber: "129", phoneNumber: "", building: "CS BUILDING", category: "Registrar", keywords: "registrar information" },
    { officeName: "REGISTRAR PROGRAMMING", localNumber: "133", phoneNumber: "", building: "CS BUILDING", category: "Registrar", keywords: "registrar programming" },
    { officeName: "REGISTRAR RECORDS-01", localNumber: "100", phoneNumber: "", building: "CS BUILDING", category: "Registrar", keywords: "registrar records" },
    { officeName: "REGISTRAR RECORDS-02", localNumber: "137", phoneNumber: "", building: "CS BUILDING", category: "Registrar", keywords: "registrar records" },
    { officeName: "SENIOR HIGH SCHOOL FACULTY ROOM", localNumber: "203", phoneNumber: "", building: "CS BUILDING", category: "Faculty", keywords: "senior high school faculty room" },
    { officeName: "SENIOR HIGH SCHOOL PRINCIPAL'S OFFICE", localNumber: "134", phoneNumber: "", building: "CS BUILDING", category: "Academic", keywords: "senior high school principal office" },
    { officeName: "TREASURER - ADMINISTRATIVE ASSISTANT", localNumber: "124", phoneNumber: "", building: "CS BUILDING", category: "Finance", keywords: "treasurer administrative assistant" },
    { officeName: "VP FINANCIAL AFFAIRS", localNumber: "152", phoneNumber: "", building: "CS BUILDING", category: "Administration", keywords: "vp financial affairs" },
    { officeName: "VP FINANCE SECRETARY", localNumber: "143", phoneNumber: "", building: "CS BUILDING", category: "Administration", keywords: "vp finance secretary" },
    { officeName: "VP ADMINISTRATIVE AFFAIRS", localNumber: "109", phoneNumber: "", building: "CS BUILDING", category: "Administration", keywords: "vp administrative affairs" },
    { officeName: "VPA SECRETARY", localNumber: "110", phoneNumber: "", building: "CS BUILDING", category: "Administration", keywords: "vpa secretary" },
    { officeName: "VPA OFFICE 2", localNumber: "111", phoneNumber: "", building: "CS BUILDING", category: "Administration", keywords: "vpa office" },
    { officeName: "VP ACADEMIC AFFAIRS", localNumber: "419", phoneNumber: "", building: "CS BUILDING", category: "Administration", keywords: "vp academic affairs" },
    { officeName: "VPAA SECRETARY", localNumber: "130", phoneNumber: "", building: "CS BUILDING", category: "Administration", keywords: "vpaa secretary" },
    { officeName: "VPAA EXECUTIVE ASSISTANT", localNumber: "138", phoneNumber: "", building: "CS BUILDING", category: "Administration", keywords: "vpaa executive assistant" },
    { officeName: "VPAA OFFICE / C.P.D. OFFICE", localNumber: "422", phoneNumber: "", building: "CS BUILDING", category: "Administration", keywords: "vpaa office cpd office" },
    { officeName: "VPAA - PROGRAMS AND STANDARDS", localNumber: "265", phoneNumber: "", building: "CS BUILDING", category: "Administration", keywords: "vpaa programs standards" },
    { officeName: "A.U.T.R.D.C. OFFICE", localNumber: "153", phoneNumber: "", building: "CS BUILDING", category: "Research", keywords: "autrdc office" },
    { officeName: "C.R.D. OFFICE", localNumber: "", phoneNumber: "", building: "CS BUILDING", category: "Research", keywords: "crd office" },
    
    // OLD CHEMISTRY BLDG.
    { officeName: "BUSINESS AFFAIRS OFFICE", localNumber: "107", phoneNumber: "", building: "OLD CHEMISTRY BLDG.", category: "Administration", keywords: "business affairs office" },
    { officeName: "CAMPUS SECURITY & SAFETY", localNumber: "103", phoneNumber: "", building: "OLD CHEMISTRY BLDG.", category: "Security", keywords: "campus security safety" },
    { officeName: "HOSPITALITY MANAGEMENT DEPT.", localNumber: "117", phoneNumber: "", building: "OLD CHEMISTRY BLDG.", category: "Academic", keywords: "hospitality management department" },
    { officeName: "HOSPITALITY MANAGEMENT LAB", localNumber: "213", phoneNumber: "", building: "OLD CHEMISTRY BLDG.", category: "Academic", keywords: "hospitality management lab" },
    { officeName: "PURCHASING/LOGISTICS", localNumber: "119", phoneNumber: "", building: "OLD CHEMISTRY BLDG.", category: "Administration", keywords: "purchasing logistics" },
    { officeName: "PFSSO DIRECTOR", localNumber: "101", phoneNumber: "", building: "OLD CHEMISTRY BLDG.", category: "Administration", keywords: "pfsso director" },
    { officeName: "PFSSO SECRETARY", localNumber: "121", phoneNumber: "", building: "OLD CHEMISTRY BLDG.", category: "Administration", keywords: "pfsso secretary" },
    { officeName: "PFSSO VENUE RESERVATION", localNumber: "105", phoneNumber: "", building: "OLD CHEMISTRY BLDG.", category: "Administration", keywords: "pfsso venue reservation" },
    { officeName: "PFSSO TRANSPORTATION", localNumber: "103", phoneNumber: "", building: "OLD CHEMISTRY BLDG.", category: "Administration", keywords: "pfsso transportation" },
    { officeName: "PFSSO HOUSEKEEPING", localNumber: "316", phoneNumber: "", building: "OLD CHEMISTRY BLDG.", category: "Maintenance", keywords: "pfsso housekeeping" },
    { officeName: "PFSSO CIVIL & ARCHITECTURAL", localNumber: "121", phoneNumber: "", building: "OLD CHEMISTRY BLDG.", category: "Maintenance", keywords: "pfsso civil architectural" },
    { officeName: "PFSSO MECHANICAL WORKS", localNumber: "315", phoneNumber: "", building: "OLD CHEMISTRY BLDG.", category: "Maintenance", keywords: "pfsso mechanical works" },
    
    // JPFRC BUILDING
    { officeName: "EDUCATION DEPT. EDUC. LAB.", localNumber: "230", phoneNumber: "", building: "JPFRC BUILDING", category: "Academic", keywords: "education department education lab" },
    { officeName: "LEARNING ASSISTANCE CENTER", localNumber: "243", phoneNumber: "", building: "JPFRC BUILDING", category: "Academic", keywords: "learning assistance center" },
    { officeName: "LEARNING ASSISTANCE CENTER 2", localNumber: "214", phoneNumber: "", building: "JPFRC BUILDING", category: "Academic", keywords: "learning assistance center" },
    { officeName: "SPED SPEECH LAB", localNumber: "246", phoneNumber: "", building: "JPFRC BUILDING", category: "Academic", keywords: "sped speech lab" },
    
    // FALCON RADIO BUILDING
    { officeName: "FALCON RADIO", localNumber: "231", phoneNumber: "", building: "FALCON RADIO BUILDING", category: "Media", keywords: "falcon radio" },
    { officeName: "BASIC EDUCATION DEPT.", localNumber: "234", phoneNumber: "", building: "FALCON RADIO BUILDING", category: "Academic", keywords: "basic education department" },
    { officeName: "ELEM & JR. HIGH REGISTRAR", localNumber: "205", phoneNumber: "", building: "FALCON RADIO BUILDING", category: "Registrar", keywords: "elementary junior high registrar" },
    { officeName: "ELEMENTARY DEPT.", localNumber: "226", phoneNumber: "", building: "FALCON RADIO BUILDING", category: "Academic", keywords: "elementary department" },
    { officeName: "ELEMENTARY FACULTY ROOM", localNumber: "217", phoneNumber: "", building: "FALCON RADIO BUILDING", category: "Faculty", keywords: "elementary faculty room" },
    { officeName: "ELEM. & JR. HIGH PRINCIPAL'S OFFICE", localNumber: "222", phoneNumber: "", building: "FALCON RADIO BUILDING", category: "Academic", keywords: "elementary junior high principal office" },
    { officeName: "JHS MAIN FACULTY ROOM", localNumber: "216", phoneNumber: "", building: "FALCON RADIO BUILDING", category: "Faculty", keywords: "jhs main faculty room" },
    { officeName: "MARIAN CENTER", localNumber: "224", phoneNumber: "", building: "FALCON RADIO BUILDING", category: "Administration", keywords: "marian center" },
    
    // ST BUILDING
    { officeName: "ACCOUNTING DEPT", localNumber: "220", phoneNumber: "", building: "ST BUILDING", category: "Academic", keywords: "accounting department" },
    { officeName: "BUSINESS ADMINISTRATION COLLEGE", localNumber: "305", phoneNumber: "", building: "ST BUILDING", category: "Academic", keywords: "business administration college" },
    { officeName: "BUSINESS ADMINISTRATION FACULTY", localNumber: "309", phoneNumber: "", building: "ST BUILDING", category: "Faculty", keywords: "business administration faculty" },
    { officeName: "BUSINESS DEAN'S OFFICE", localNumber: "308", phoneNumber: "", building: "ST BUILDING", category: "Academic", keywords: "business dean office" },
    { officeName: "CELAP LIBRARY", localNumber: "235", phoneNumber: "", building: "ST BUILDING", category: "Library", keywords: "celap library" },
    { officeName: "CHEMISTRY DEPT.", localNumber: "417", phoneNumber: "", building: "ST BUILDING", category: "Academic", keywords: "chemistry department" },
    { officeName: "CUSTOM ADMINISTRATION DEPT", localNumber: "204", phoneNumber: "", building: "ST BUILDING", category: "Academic", keywords: "custom administration department" },
    { officeName: "ENGINEERING LIBRARY", localNumber: "240", phoneNumber: "", building: "ST BUILDING", category: "Library", keywords: "engineering library" },
    { officeName: "ENGLISH DEPT", localNumber: "303", phoneNumber: "", building: "ST BUILDING", category: "Academic", keywords: "english department" },
    { officeName: "FINANCE & ECONOMICS DEPT", localNumber: "206", phoneNumber: "", building: "ST BUILDING", category: "Academic", keywords: "finance economics department" },
    { officeName: "MANAGEMENT DEPT", localNumber: "219", phoneNumber: "", building: "ST BUILDING", category: "Academic", keywords: "management department" },
    { officeName: "MARKETING DEPT", localNumber: "218", phoneNumber: "", building: "ST BUILDING", category: "Academic", keywords: "marketing department" },
    { officeName: "MATH DEPT", localNumber: "244", phoneNumber: "", building: "ST BUILDING", category: "Academic", keywords: "math department" },
    { officeName: "MODULAR SCIENCE LAB", localNumber: "", phoneNumber: "", building: "ST BUILDING", category: "Academic", keywords: "modular science lab" },
    { officeName: "NURSING DEPT", localNumber: "237", phoneNumber: "", building: "ST BUILDING", category: "Academic", keywords: "nursing department" },
    { officeName: "OFFICE OF CULTURAL AFFAIRS", localNumber: "201", phoneNumber: "", building: "ST BUILDING", category: "Student Affairs", keywords: "office cultural affairs" },
    { officeName: "OFFICE OF STUDENT AFFAIRS", localNumber: "202", phoneNumber: "", building: "ST BUILDING", category: "Student Affairs", keywords: "office student affairs" },
    { officeName: "OFFICE OF STUDENT DEVELOPMENT", localNumber: "208", phoneNumber: "", building: "ST BUILDING", category: "Student Affairs", keywords: "office student development" },
    { officeName: "OFFICE OF STUDENT AFFAIRS DIRECTOR", localNumber: "238", phoneNumber: "", building: "ST BUILDING", category: "Student Affairs", keywords: "office student affairs director" },
    { officeName: "PHARMACY DEPT", localNumber: "227", phoneNumber: "", building: "ST BUILDING", category: "Academic", keywords: "pharmacy department" },
    { officeName: "PHARMACY LABORATORY", localNumber: "", phoneNumber: "", building: "ST BUILDING", category: "Academic", keywords: "pharmacy laboratory" },
    { officeName: "PSYCHOLOGY DEPT", localNumber: "304", phoneNumber: "", building: "ST BUILDING", category: "Academic", keywords: "psychology department" },
    { officeName: "SCIENCE DEAN'S OFFICE", localNumber: "223", phoneNumber: "", building: "ST BUILDING", category: "Academic", keywords: "science dean office" },
    { officeName: "SOCIAL SCIENCE DEPT", localNumber: "223", phoneNumber: "", building: "ST BUILDING", category: "Academic", keywords: "social science department" },
    { officeName: "SPEECH LAB", localNumber: "225", phoneNumber: "", building: "ST BUILDING", category: "Academic", keywords: "speech lab" },
    
    // L.W. BUILDING
    { officeName: "COLLEGE OF NURSING", localNumber: "", phoneNumber: "", building: "L.W. BUILDING", category: "Academic", keywords: "college nursing" },
    { officeName: "LIBRARY - MAIN", localNumber: "248", phoneNumber: "", building: "L.W. BUILDING", category: "Library", keywords: "library main" },
    { officeName: "LIBRARY - SECOND FLOOR", localNumber: "131", phoneNumber: "", building: "L.W. BUILDING", category: "Library", keywords: "library second floor" },
    
    // OZ BUILDING
    { officeName: "AUDIOVISUAL ROOM - 3RD FLR.", localNumber: "228", phoneNumber: "", building: "OZ BUILDING", category: "Media", keywords: "audiovisual room 3rd floor" },
    { officeName: "CHEMICAL ENGINEERING DEPT.", localNumber: "410", phoneNumber: "", building: "OZ BUILDING", category: "Academic", keywords: "chemical engineering department" },
    { officeName: "CHEMICAL ENGINEERING LAB", localNumber: "416", phoneNumber: "", building: "OZ BUILDING", category: "Academic", keywords: "chemical engineering lab" },
    { officeName: "CHEMISTRY DEPT.", localNumber: "428", phoneNumber: "", building: "OZ BUILDING", category: "Academic", keywords: "chemistry department" },
    { officeName: "CHEMISTRY LAB", localNumber: "413", phoneNumber: "", building: "OZ BUILDING", category: "Academic", keywords: "chemistry lab" },
    { officeName: "CIVIL ENGINEERING DEPT.", localNumber: "407", phoneNumber: "", building: "OZ BUILDING", category: "Academic", keywords: "civil engineering department" },
    { officeName: "CIVIL ENGINEERING LAB", localNumber: "425", phoneNumber: "", building: "OZ BUILDING", category: "Academic", keywords: "civil engineering lab" },
    { officeName: "COMPUTER ENGINEERING DEPT.", localNumber: "409", phoneNumber: "", building: "OZ BUILDING", category: "Academic", keywords: "computer engineering department" },
    { officeName: "COMPUTER ENGG DISPENSING ROOM", localNumber: "421", phoneNumber: "", building: "OZ BUILDING", category: "Academic", keywords: "computer engineering dispensing room" },
    { officeName: "E.C.E. LAB.", localNumber: "425", phoneNumber: "", building: "OZ BUILDING", category: "Academic", keywords: "ece lab" },
    { officeName: "ELECTRICAL ENGINEERING DEPT.", localNumber: "408", phoneNumber: "", building: "OZ BUILDING", category: "Academic", keywords: "electrical engineering department" },
    { officeName: "ELECTRICAL ENGINEERING LAB", localNumber: "403", phoneNumber: "", building: "OZ BUILDING", category: "Academic", keywords: "electrical engineering lab" },
    { officeName: "ELECTRONICS ENGINEERING DEPT.", localNumber: "403", phoneNumber: "", building: "OZ BUILDING", category: "Academic", keywords: "electronics engineering department" },
    { officeName: "ENGINEERING DEAN SECRETARY", localNumber: "405", phoneNumber: "", building: "OZ BUILDING", category: "Academic", keywords: "engineering dean secretary" },
    { officeName: "ENGINEERING DEANS OFFICE", localNumber: "406", phoneNumber: "", building: "OZ BUILDING", category: "Academic", keywords: "engineering dean office" },
    { officeName: "INDUSTRIAL ENGOMECH ENGG LAB", localNumber: "401", phoneNumber: "", building: "OZ BUILDING", category: "Academic", keywords: "industrial engineering mechanical engineering lab" },
    { officeName: "INDUSTRIAL ENGINEERING DEPT", localNumber: "", phoneNumber: "", building: "OZ BUILDING", category: "Academic", keywords: "industrial engineering department" },
    { officeName: "MINING GEOLOGY CERAMICS ENGG DEPT", localNumber: "411", phoneNumber: "", building: "OZ BUILDING", category: "Academic", keywords: "mining geology ceramics engineering department" },
    { officeName: "MECH. ENGINEERING I.P.C. ROOM", localNumber: "402", phoneNumber: "", building: "OZ BUILDING", category: "Academic", keywords: "mechanical engineering ipc room" },
    { officeName: "MECHANICAL ENGINEERING DEPT", localNumber: "414", phoneNumber: "", building: "OZ BUILDING", category: "Academic", keywords: "mechanical engineering department" },
    { officeName: "PHYSICS DEPT", localNumber: "400", phoneNumber: "", building: "OZ BUILDING", category: "Academic", keywords: "physics department" },
    { officeName: "PHYSICS LAB", localNumber: "412", phoneNumber: "", building: "OZ BUILDING", category: "Academic", keywords: "physics lab" },
    
    // SV BUILDING
    { officeName: "A.U.F.E.A OFFICE", localNumber: "", phoneNumber: "", building: "SV BUILDING", category: "Administration", keywords: "aufea office" },
    { officeName: "ADAMSON UNIVERSITY MUSEUM", localNumber: "323", phoneNumber: "", building: "SV BUILDING", category: "Cultural", keywords: "adamson university museum" },
    { officeName: "ALUMNI OFFICE", localNumber: "303", phoneNumber: "", building: "SV BUILDING", category: "Alumni", keywords: "alumni office" },
    { officeName: "COLLEGE OF LAW", localNumber: "311", phoneNumber: "", building: "SV BUILDING", category: "Academic", keywords: "college law" },
    { officeName: "COLLEGE OF LAW LIBRARY", localNumber: "324", phoneNumber: "", building: "SV BUILDING", category: "Library", keywords: "college law library" },
    { officeName: "COMPUTER SCIENCE DEPT.", localNumber: "305", phoneNumber: "", building: "SV BUILDING", category: "Academic", keywords: "computer science department" },
    { officeName: "FALCONS NEST", localNumber: "139", phoneNumber: "", building: "SV BUILDING", category: "Food", keywords: "falcons nest" },
    { officeName: "GRADUATE SCHOOL DEANS OFFICE", localNumber: "317", phoneNumber: "", building: "SV BUILDING", category: "Academic", keywords: "graduate school dean office" },
    { officeName: "GRADUATE SCHOOL FACULTY ROOM", localNumber: "334", phoneNumber: "", building: "SV BUILDING", category: "Faculty", keywords: "graduate school faculty room" },
    { officeName: "GRADUATE SCHOOL LIBRARY", localNumber: "313", phoneNumber: "", building: "SV BUILDING", category: "Library", keywords: "graduate school library" },
    { officeName: "I.T. & M.", localNumber: "335", phoneNumber: "", building: "SV BUILDING", category: "IT", keywords: "it m" },
    { officeName: "OFFICE FOR ATHLETIC DEVELOPMENT", localNumber: "304", phoneNumber: "", building: "SV BUILDING", category: "Athletics", keywords: "office athletic development" },
    { officeName: "OFFICE FOR INSTITUTIONAL ADVANCEMENT", localNumber: "314", phoneNumber: "", building: "SV BUILDING", category: "Administration", keywords: "office institutional advancement" },
    { officeName: "O.V.I.M / VINCENTIAN CENTER", localNumber: "315", phoneNumber: "", building: "SV BUILDING", category: "Administration", keywords: "ovim vincentian center" },
    { officeName: "PHYSICAL EDUCATION DEPT", localNumber: "320", phoneNumber: "", building: "SV BUILDING", category: "Athletics", keywords: "physical education department" },
    
    // PHONE DIRECTORY ENTRIES
    { officeName: "ADMISSIONS OFFICE", localNumber: "", phoneNumber: "8557-1823", building: "", category: "Admissions", keywords: "admissions office" },
    { officeName: "ADMISSIONS FAX", localNumber: "", phoneNumber: "8521-6541", building: "", category: "Admissions", keywords: "admissions fax" },
    { officeName: "AVPAA OFFICE", localNumber: "", phoneNumber: "8521-6632", building: "", category: "Administration", keywords: "avpaa office" },
    { officeName: "BASIC EDUCATION DEPARTMENT", localNumber: "", phoneNumber: "8523-5784", building: "", category: "Academic", keywords: "basic education department" },
    { officeName: "BUDGET OFFICE", localNumber: "", phoneNumber: "8524-8003", building: "", category: "Finance", keywords: "budget office" },
    { officeName: "CAMPUS MINISTRY", localNumber: "", phoneNumber: "8523-2626", building: "", category: "Campus Ministry", keywords: "campus ministry" },
    { officeName: "CAMPUS SECURITY AND SAFETY", localNumber: "", phoneNumber: "8559-3394", building: "", category: "Security", keywords: "campus security safety" },
    { officeName: "CASH MANAGEMENT OFFICE", localNumber: "", phoneNumber: "8516-4859", building: "", category: "Finance", keywords: "cash management office" },
    { officeName: "COLLEGE OF NURSING", localNumber: "", phoneNumber: "8536-2099", building: "", category: "Academic", keywords: "college nursing" },
    { officeName: "COLLEGE OF PHARMACY", localNumber: "", phoneNumber: "8522-7951", building: "", category: "Academic", keywords: "college pharmacy" },
    { officeName: "CULTURAL AFFAIR OFFICE", localNumber: "", phoneNumber: "8521-8609", building: "", category: "Student Affairs", keywords: "cultural affair office" },
    { officeName: "CUSTOM ADMINISTRATION", localNumber: "", phoneNumber: "8522-0141", building: "", category: "Academic", keywords: "custom administration" },
    { officeName: "FACULTY SAVINGS / TESLAFU", localNumber: "", phoneNumber: "8522-0121", building: "", category: "Finance", keywords: "faculty savings teslafu" },
    { officeName: "FINANCE OFFICE", localNumber: "", phoneNumber: "8535-5246", building: "", category: "Finance", keywords: "finance office" },
    { officeName: "GRADUATE SCHOOL", localNumber: "", phoneNumber: "8522-0016", building: "", category: "Academic", keywords: "graduate school" },
    { officeName: "GUIDANCE & PLACEMENT", localNumber: "", phoneNumber: "8523-2596", building: "", category: "Guidance", keywords: "guidance placement" },
    { officeName: "H.R.M.D.-MAIN", localNumber: "", phoneNumber: "8522-0550", building: "", category: "HR", keywords: "hrmd main" },
    { officeName: "LOGISTICS/PURCHASING", localNumber: "", phoneNumber: "8524-3027", building: "", category: "Administration", keywords: "logistics purchasing" },
    { officeName: "MARIAN CENTER", localNumber: "", phoneNumber: "8521-1200", building: "", category: "Administration", keywords: "marian center" },
    { officeName: "O.U.R.", localNumber: "", phoneNumber: "8526-1743", building: "", category: "Administration", keywords: "our" },
    { officeName: "PHYSICAL FACILITIES OFFICE", localNumber: "", phoneNumber: "8535-0857", building: "", category: "Maintenance", keywords: "physical facilities office" },
    { officeName: "PRESIDENT'S OFFICE", localNumber: "", phoneNumber: "8521-6890", building: "", category: "Administration", keywords: "president office" },
    { officeName: "PRESIDENT OFFICE TELEFAX", localNumber: "", phoneNumber: "8522-5536", building: "", category: "Administration", keywords: "president office telefax" },
    { officeName: "REGISTRAR'S OFFICE", localNumber: "", phoneNumber: "8522-5528", building: "", category: "Registrar", keywords: "registrar office" },
    { officeName: "REGISTRAR'S OFFICE TELEFAX", localNumber: "", phoneNumber: "0400-0190", building: "", category: "Registrar", keywords: "registrar office telefax" },
    { officeName: "SECURITY OFFICE", localNumber: "", phoneNumber: "8516-3311", building: "", category: "Security", keywords: "security office" }
];
